##访问端口
#server:
#  port: 8080
#  servlet:
#    context-path: /plc

#mybatis配置
#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  config-location: classpath:mapper/config/sqlMapConfig.xml
#  type-aliases-package: com.modbus.plc.bean

#数据库
spring:
  jmx:
    default-domain: plc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/plc?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000

  mvc:
    static-path-pattern: /static/**

  thymeleaf:
    cache: false
